version: '3.3'
services:
  posweb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'posweb'
      MYSQL_USER: 'posweb'
      MYSQL_PASSWORD: 'posweb'
      MYSQL_ROOT_PASSWORD: 'posweb'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    # expose:
      # Opens port 3306 on the container
      # - '3306'
      # Where our data will be persisted
    volumes:
      - posweb-db:/var/lib/mysql
# Names our volume
volumes:
  posweb-db: